# encoding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Requires Vagrant 1.6+, tested on Vagrant 1.6.3

Vagrant.configure("2") do |config|
  # use a Ubuntu 14.04 LTS instance (64-bit)
  config.vm.box = "ubuntu/trusty64"
  config.ssh.forward_agent = true

  # we need more memory, or the Python processes will crash when loading the CSV
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1536"]
  end

  # run the setup.sh during initial provisioning and the runserver.sh always
  #config.vm.provision "file", source: "requirements-without-packages.txt", destination: "~/requirements-without-packages.txt"
  config.vm.provision "shell", path: "setup_system.sh", privileged: true
  config.vm.provision "shell", path: "setup_project.sh", privileged: false
  config.vm.provision "shell", path: "runserver.sh", run: "always", privileged: false

  # forward host port 9999 to guest port 8000 to make the server accessible as http://localhost:9999/ on the host
  config.vm.network "forwarded_port", guest: 8000, host: 9999

end
